// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: distributed-auth-system/transaction.proto

package distributed_auth_system

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TransactionRequest represents a request to handle a transaction
type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_distributed_auth_system_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distributed_auth_system_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_distributed_auth_system_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TransactionRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// TransactionResponse represents a response from handling a transaction
type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_distributed_auth_system_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distributed_auth_system_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_distributed_auth_system_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_distributed_auth_system_transaction_proto protoreflect.FileDescriptor

const file_distributed_auth_system_transaction_proto_rawDesc = "" +
	"\n" +
	")distributed-auth-system/transaction.proto\"<\n" +
	"\x12TransactionRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"/\n" +
	"\x13TransactionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2T\n" +
	"\x12TransactionService\x12>\n" +
	"\x11HandleTransaction\x12\x13.TransactionRequest\x1a\x14.TransactionResponseBFZDgithub.com/GooseFuse/distributed-auth-system;distributed_auth_systemb\x06proto3"

var (
	file_distributed_auth_system_transaction_proto_rawDescOnce sync.Once
	file_distributed_auth_system_transaction_proto_rawDescData []byte
)

func file_distributed_auth_system_transaction_proto_rawDescGZIP() []byte {
	file_distributed_auth_system_transaction_proto_rawDescOnce.Do(func() {
		file_distributed_auth_system_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_distributed_auth_system_transaction_proto_rawDesc), len(file_distributed_auth_system_transaction_proto_rawDesc)))
	})
	return file_distributed_auth_system_transaction_proto_rawDescData
}

var file_distributed_auth_system_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_distributed_auth_system_transaction_proto_goTypes = []any{
	(*TransactionRequest)(nil),  // 0: TransactionRequest
	(*TransactionResponse)(nil), // 1: TransactionResponse
}
var file_distributed_auth_system_transaction_proto_depIdxs = []int32{
	0, // 0: TransactionService.HandleTransaction:input_type -> TransactionRequest
	1, // 1: TransactionService.HandleTransaction:output_type -> TransactionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_distributed_auth_system_transaction_proto_init() }
func file_distributed_auth_system_transaction_proto_init() {
	if File_distributed_auth_system_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_distributed_auth_system_transaction_proto_rawDesc), len(file_distributed_auth_system_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_distributed_auth_system_transaction_proto_goTypes,
		DependencyIndexes: file_distributed_auth_system_transaction_proto_depIdxs,
		MessageInfos:      file_distributed_auth_system_transaction_proto_msgTypes,
	}.Build()
	File_distributed_auth_system_transaction_proto = out.File
	file_distributed_auth_system_transaction_proto_goTypes = nil
	file_distributed_auth_system_transaction_proto_depIdxs = nil
}
