version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  auth-node-1:
    build: .
    container_name: auth-node-1
    environment:
      - NODE_ID=auth-node-1
      - REDIS_URL=redis:6379
      - PORT=6333
    volumes:
      - ./data/node-1:/app/data
      - ./secrets:/app/secrets
    depends_on:
      - redis

  auth-node-2:
    build: .
    container_name: auth-node-2
    environment:
      - NODE_ID=auth-node-2
      - REDIS_URL=redis:6379
      - PORT=6333
    volumes:
      - ./data/node-2:/app/data
      - ./secrets:/app/secrets
    depends_on:
      - redis

  auth-node-3:
    build: .
    container_name: auth-node-3
    environment:
      - NODE_ID=auth-node-3
      - REDIS_URL=redis:6379
      - PORT=6333
    volumes:
      - ./data/node-3:/app/data
      - ./secrets:/app/secrets
    depends_on:
      - redis

  demo-node:
    build: ./client/
    container_name: demo-node
    depends_on:
      - auth-node-1
      - auth-node-2
      - auth-node-3

volumes:
  redis-data:
